### ISSUE TITLE
float too large to pack with f format 

### ISSUE THREAD

**Issue by MAVProxyUser** [ArduPilot/MAVProxy#10]
The following error seems to trip up the proxy with in a few minutes of running. What is the cause? Is it because my longitude has a negative in it? 

MAVProxyUser@ubuntu:~/ardupilot-mega/Tools/autotest/pysim$ python sim_multicopter.py  --frame=+ --rate=400 --home=xx.xxxxxx,-xx.xxxxx,250,0 --wind=15,25,1
Simulating 4 motors for frame +
Starting at lat=xx.xxxxxx lon=-xx.xxxxxx alt=250.0 heading=0.0
Traceback (most recent call last):
  File "sim_multicopter.py", line 177, in <module>
    sim_send(m, a)
  File "sim_multicopter.py", line 36, in sim_send
    fg_out.send(fdm.pack())
  File "/home/MAVProxyUser/ardupilot-mega/Tools/autotest/pysim/../../../../mavlink/pymavlink/fgFDM.py", line 211, in pack
    return struct.pack(self.pack_string, *self.values)
OverflowError: float too large to pack with f format

$ cat /etc/issue
Ubuntu 12.10 \n \l

$ python -V
Python 2.7.3

$ uname -a 
Linux ubuntu 3.5.0-18-generic #29-Ubuntu SMP Fri Oct 19 10:27:31 UTC 2012 i686 i686 i686 GNU/Linux

**Comment by amilcarlucas** [comment]
Never saw this one, I think it is fixed now

**Comment by amilcarlucas** [comment]
Works in the latest release. Closing it now. Please reopen if the problem persists in the latest release.
