### ISSUE TITLE
Create a Releases Tab for Windows MAVProxy

### ISSUE THREAD

**Issue by hendjoshsr71** [ArduPilot/MAVProxy#1090]
It would be nice to have the Release tab available that would have the latest version for download. It would be easier than grabbing the `.exe.` from the last PRs autotest archive. 

Like Mission Planner has:
![image](https://user-images.githubusercontent.com/69225461/182322316-1166dc53-e146-428e-9995-85f7ff28aeec.png)

**Comment by stephendade** [comment]
Done in #1114

**Comment by hendjoshsr71** [comment]
Thanks!
