### ISSUE TITLE
What does "APM: PreArm: RC not calibrated" mean?

### ISSUE THREAD

**Issue by nickponline** [ArduPilot/MAVProxy#11]
I'm running an ArduCopter SITL and when I try and ARM the motors by sending command 400 I get:

APM: PreArm: RC not calibrated

Is there something I need to do first before I arm the motors?

**Comment by jainakshay91** [comment]
Hi , 
@rmackay9 where exactly in the simulator do I enter the command: "param set ARMIN_CHECK 0"? I am running it from linux command line. After SITL waits for a connection I run the simple_goto.py code.  But I have been running into the PreArm: RC not calibrated error. I have tried entering the command after SITL reaches the stage where it waits for the connection. But it has not worked so far. Kindly let me know if I am missing something here. 

Best 
Akshay

**Comment by magicrub** [comment]
I've never hear of simple_goto.py, where/why are you running that? Is it on
a wiki somewhere?

**Comment by jainakshay91** [comment]
@magicrub sorry that I did not mention this in my comment, but I am working with dronekit-python and simple_goto.py is an example script in dronekit-python. I am trying to get it to work with SITL, but apparently I am unable to resolve the Prearm: RC not calibrated error.

**Comment by magicrub** [comment]
if you just can't get passed a given pre-arm, then a workaround would be to
disable that prearm check.Fine for SITL but not recommended for an actual
flight.

**Comment by rmackay9** [comment]
@jainakshay91, checkout this page on the wiki and search for "Parameters". 
http://python.dronekit.io/guide/vehicle_state_and_parameters.html#vehicle-information

Looks like you could add a line like this into the python script to turn off the arming check
vehicle.parameters['ARMING_CHECK']=0

**Comment by jainakshay91** [comment]
@rmackay9 awesome , fantastic... oh yeah! Damn I should have seen that one.. anyways thanks a lot man :)

**Comment by GusBus4** [comment]
I just solved an issue I had, I see my default param file was not found. Editing the link fixed all the issues. As @rmackay9 said, certain parameters need to be set for the SITL system to think it has been calibrated.

**Comment by FahadManzoor** [comment]
Hello
we are making Quadcopter using APM 2.8 and ESC of 30A(MR.RC 30A Brushless ESC Speed Controller _A0964) this is our final year project and it is first time we are working on such thing and we are facing a problem:
we have tested the motors using transmitter and receiver without the use of APM 
and now we have configured the APM and we are running the motors using Connections of APM with ESC but the motors are just twitching and beep beep beep beep.............. sound is ringing from ESCs and this beep is not stopping for a minute even we are moving the throtle....
![esc](https://cloud.githubusercontent.com/assets/25575854/22634571/d175038a-ec4c-11e6-8a69-0722961cb989.jpg)
Please Suggest some sort of solutions for this....

**Comment by peterbarker** [comment]
On Sun, 5 Feb 2017, FahadManzoor wrote:

> we are making Quadcopter using APM 2.8 and ESC of 30A(MR.RC 30A Brushless
> ESC Speed Controller _A0964) this is our final year project and it is first
> time we are working on such thing and we are facing a problem:
> we have tested the motors using transmitter and receiver without the use of
> APM
> and now we have configured the APM and we are running the motors using
> Connections of APM with ESC but the motors are just twitching and beep beep
> beep beep.............. sound is ringing from ESCs and this beep is not
> stopping for a minute even we are moving the throtle....
> esc
> Please Suggest some sort of solutions for this....

The beeping is simply a warning from the ESCs that they are bored.  You 
*can* stop them doing that, but I suggest you don't, it is a useful 
diagnostic.  Once they start to receive signals they won't beep.

"RC not calibrated" means that you haven't done all of the calibration 
procedures required to make the autopilot safe to control an aircraft.

Have you followed the first-time setup on the Wiki? 
http://ardupilot.org/copter/docs/initial-setup.html

I strongly suggest that you purchase a PixHawk device in place of your APM 
device.  The APM2.8 is an ancient 8-bit-microntroller-based machine 
incapable of running a lot of the modern ArduCopter code.
