### ISSUE TITLE
Current state of the project?

### ISSUE THREAD

**Issue by booo** [ArduPilot/MAVProxy#1169]
Hi,

what is the current state of this project? We would like to use the project and contribute to the project but we have the feeling that contributions are not reviewed or valued at the moment. I would appreciate some honest words about the capabilities of the current "main developers" in regards to contributions.

Thanks for your time.

Best Philipp

**Comment by peterbarker** [comment]
On Sat, 25 Mar 2023, Philipp Borgers wrote:

> what is the current state of this project? We would like to use the project and contribute to the project but we have the feeling that contributions are not reviewed or valued at the moment. I would appreciate some honest words about the capabilities of the current "main developers" in regards to contributions.

We are admittedly not very good at reviewing and merging PRs or looking 
through issues.

Not because we don't value contributions but because we're busy - that's a 
familiar tale.

Is there something in particular you were looking at doing?

> Best Philipp

Peter

**Comment by rmackay9** [comment]
No response in a while so closing.
