### ISSUE TITLE
MAVProxy and Vicon with Ardupilot

### ISSUE THREAD

**Issue by Grace1E** [ArduPilot/MAVProxy#1204]
Hello,
Thank you for the work great work on this project.
I'm requesting for assistance with the problem I'm having when I attempt to load the 'vicon' module in MAVProxy; please see below what I get:

MAV> module load vicon
No module named 'pyvicon'
Traceback (most recent call last):
  File "mavproxy.py", line 681, in import_package
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "modules\mavproxy_vicon.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyvicon'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mavproxy.py", line 528, in load_module
  File "mavproxy.py", line 684, in import_package
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "modules\mavproxy_vicon.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyvicon'

No module named 'vicon'
Traceback (most recent call last):
  File "mavproxy.py", line 681, in import_package
ModuleNotFoundError: No module named 'vicon'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mavproxy.py", line 528, in load_module
  File "mavproxy.py", line 684, in import_package
ModuleNotFoundError: No module named 'vicon'

Failed to load module: No module named 'vicon'.

I was following the instructions from:
https://ardupilot.org/copter/docs/common-vicon-for-nongps-navigation.html

Thanks!

**Comment by stephendade** [comment]
Have you confirmed that you've installed pyvicon? Se ``pip3 list`` to see a list of install python packages.

**Comment by Grace1E** [comment]
Thank you for the response.
Yes, I confirmed the installation of pyvicon:

pyvicon                   0.1

**Comment by stephendade** [comment]
Try ``set moddebug 3`` before loading the module. It should show more detailed info.

**Comment by Grace1E** [comment]
It gives the previously referenced response after using 'set moddebug 3'.
Before that it simply gives:
Failed to load module: No module named 'vicon'. Use 'set moddebug 3' in the MAVProxy console to enable traceback.

**Comment by stephendade** [comment]
Are you running this under Windows?

**Comment by Grace1E** [comment]
Yes, Windows 10

**Comment by stephendade** [comment]
It looks like you're running MAVProxy from the installer?

The vicon package isn't included in the installer, which is why it is not loading.

You will need to run MAVProxy from source, see https://ardupilot.org/mavproxy/docs/development/mavdevenvwindows.html

**Comment by Grace1E** [comment]
Thank you for the help.
I did as advised above, however it still didn't load.
But after moving some .dll files associated with Vicon to the C:\Windows\System32 and C:\Windows\System64, it was successful in loading the module.
