### ISSUE TITLE
fakegps appears to set incorrect time

### ISSUE THREAD

**Issue by shancock884** [ArduPilot/MAVProxy#1211]
When using fakegps, I noticed that the time being reported by my drone was approx 18 hrs in the past.
I believe the issue is something to do with the maths on lines 83-84 of mavproxy_fakegps.py
        epoch = 86400*(10*365 + (1980-1969)/4 + 1 + 6 - 2) - leapseconds
        epoch_seconds = int(tnow - epoch)
I replaced these with:
        epoch_seconds = int(tnow - 315964800 + leapseconds)
based on what is described on this website: https://www.andrews.edu/~tzs/timeconv/timealgorithm.html
This change appeared to give correct time.

(As an aside, I think the variable names tnow/epoch_seconds might be better named t_unix and t_gps or similar).

**Comment by tridge** [comment]
fixed, thanks!
