### ISSUE TITLE
Allow easily changing to Rover's circle mode from command line

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MAVProxy#1275]
For most modes I can just type in the mode name and MAVProxy will switch the vehicle to that mode but this doesn't seem to work for Rover's circle mode.

**Comment by stephendade** [comment]
You'll need the latest GitHub pymavlink installed. The ``pip install pymavlink`` (V2.4.40) doesn't currently have the circle mode patch I added.

We should probably do another pymavlink release....

**Comment by rmackay9** [comment]
OK thanks.  I'll close this then 'cuz it should be resolved with the next official pymavlink release.
