### ISSUE TITLE
KML list doesn't work

### ISSUE THREAD

**Issue by Ryanf55** [ArduPilot/MAVProxy#1388]
https://github.com/ArduPilot/ardupilot_wiki/blob/master/mavproxy/source/docs/modules/kmlread.rst#layers

```
STABILIZE> kml list
STABILIZE> Usage: kml <clear | load (filename) | layers | toggle (layername) | fence (layername)> | snapfence | snapwp
```

You can't list what's loaded in `kml` with `kml list` anymore.

**Comment by peterbarker** [comment]
> > > > I wonder if this should be raised in the [MAVProxy issues list](https://github.com/ArduPilot/MAVProxy/issues)?
> > > 
> > > 
> > > I would think to raise the issue where the source code is, but I don't know the convention.
> > 
> > 
> > I think Randy's point was that this is the `ardupilot_wiki` issues list... not entirely related to MAVProxy.
> 
> Right. Can either of you move the issue?

Apparently yes.

**Comment by Hwurzburg** [comment]
moved so closing

**Comment by peterbarker** [comment]
> moved so closing

You aactually closed this in the destination repository.  I believe it's complete anyway, so *shrug*
