### ISSUE TITLE
Siyi: typo in pitch control

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MAVProxy#1409]
While reviewing the MAVProxy Siyi gimbal controller to see if there are parts we should port back to the AP C++ driver I noticed this little bug in the update_target function.  Note how the 2nd line is re-using the yaw controller to correct for pitch

```
        self.yaw_rate = self.yaw_controller.run(err_yaw, los_yaw_rate)
        self.pitch_rate = self.yaw_controller.run(err_pitch, los_pitch_rate)
```

**Comment by tridge** [comment]
fixed, thanks!
