### ISSUE TITLE
opencv is required for "module load map"

### ISSUE THREAD

**Issue by captcha1** [ArduPilot/MAVProxy#1415]
I tried to do "module load map", but "import cv2" failed, so I had to install (python3) opencv ...

**Comment by peterbarker** [comment]
> I tried to do "module load map", but "import cv2" failed, so I had to install (python3) opencv ...

We don't install these dependencies by default as MAVProxy is often used in "headless" mode, flying on companion computers and acting as a mavlink router and providing random other services.

If we installed all packages required by all extension modules we'd be installing a *lot* of stuff!

Thanks for the report, anyway.  Perhaps we need to make this current state of affairs clearer somehow - catch the import error and emit a nice message of some sort...
