### ISSUE TITLE
SecureCommand module not working properly on windows

### ISSUE THREAD

**Issue by 4dri4anxD** [ArduPilot/MAVProxy#1423]
**Problem description:**
When trying to remove public keys from a flight controller running ardupilot firmware I ran this command "module load SecureCommand" and got "Please install monocypher with: python3 -m pip install pymonocypher" message.
pymonocypher is already installed via "py -m pip install pymonocypher".
It seems like pymonocypher is not being included by default when building.

**Expected behavior:**
When running "module load SecureCommand" command it should load the module without no problems.

**Current behavior:**
Got "Please install monocypher with: python3 -m pip install pymonocypher" message after running the command.

**Operating system:** 
Windows 10

**Python version:**
3.12.14

**pip version:**
24.0

**Steps to reproduce**
1. Download and install the [latest release](https://firmware.ardupilot.org/Tools/MAVProxy/) of MavProxy for windows
2. Connect a Flight Controller to the Computer by USB
3. Open a command prompt window
4. Run "mavproxy --master=COMx" command (x is replaced by the port assigned to the flight controller)
5. Run "module load SecureCommand"

**Workaround:**
Digging a little I found [this comment](https://github.com/ArduPilot/MAVProxy/issues/181#issuecomment-131489544) which says that mavlink does not use the python environment on windows, thus, external libraries needs to be pasted in the MavProxy/_internal/ directory.
So I copied and pasted pymonocypher library folder and .pyd file into the MavProxy/_internal/ directory and then ran module load SecureCommand but got the same error message.
Then I built mavproxy [v1.8.70](https://github.com/ArduPilot/MAVProxy/tree/v1.8.70) (by running MAVProxyWinBuild.bat file) and then copied and pasted the same library folder and the .pyd file into MavProxy/_internal/ directory and then ran SecureCommand and it worked.
At first I got Mavproxy v1.8.69 from [here](https://firmware.ardupilot.org/Tools/MAVProxy/) (the latest release windows installer).

**Comment by stephendade** [comment]
>  It seems like pymonocypher is not being included by default when building.

Correct, it's not currently included. I'll need to find a way to collate all the various module requirements into a single place and reference that in the build.
