### ISSUE TITLE
Multiprocessing error

### ISSUE THREAD

**Issue by djnugent** [ArduPilot/MAVProxy#178]
This commit interferes with any dronekit script that uses multiprocessing.
Having to revert to fix the issue.
https://github.com/Dronecode/MAVProxy/commit/680f9064a4c655f0bf20975fa604f9af300f15d1

**Comment by amilcarlucas** [comment]
The multiprocessing infrastructure has been reworked, can you test the latest version?

**Comment by amilcarlucas** [comment]
Works in the latest release. Closing it now. Please reopen if the problem persists in the latest release.
