### ISSUE TITLE
mavlogdump.py : unable to export .bin to .csv

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/MAVProxy#201]
this works /(see types)
mavlogdump.py "/home/andre/test2, trimdata.BIN" --types POS,CAM 

this does not:
mavlogdump.py "/home/andre/Linux/Observer test2, trimdata.BIN" --types POS,CAM --format csv

once format = csv, I get an error with first type mentioned, regardless of the actual type(s)

Traceback (most recent call last):
  File "/usr/local/bin/mavlogdump.py", line 73, in <module>
    fields += [type + '.' + x for x in inspect.getargspec(getattr(mavutil.mavlink, typeClass).**init**).args[1:]]
AttributeError: 'module' object has no attribute 'MAVLink_pos_message'

**Comment by stephendade** [comment]
mavlogdump is part of mavlink (https://github.com/mavlink/mavlink), so you will have better luck posting over there.

**Comment by peterbarker** [comment]
I believe this is fixed now, anyway!
