### ISSUE TITLE
Get rid of cv2.cv in order to support OpenCV3

### ISSUE THREAD

**Issue by shadow1runner** [ArduPilot/MAVProxy#257]
I'm developing using OpenCV3 (master, compiled from sources). MavProxy's map does not like OpenCV3, mainly because of the outdated `import cv2.cv as cv` (and the respective legacy C-bindings of OpenCV), as OpenCV3 [got rid of cv2.cv](http://stackoverflow.com/a/26859781/2559632).

I don't think that the C-bindings dependency is still necessary (open for discussion) and am currently working (on an almost done) PR which allows the use OpenCV3 alongside OpenCV2 for the `map module`.

**Comment by Georacer** [comment]
Thanks for that!
