### ISSUE TITLE
map module - first time trouble.

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/MAVProxy#274]
I installed mavproxy on a laptop, then use map and console module for the first time while in the field (no network)

the screenshot below is what fills the terminal.

![screenshot from 2016-05-10 12-19-46](https://cloud.githubusercontent.com/assets/1468842/15153592/0f21c78e-16da-11e6-8b9e-b74d342ee0a3.png)

map will not show up (even a blank map with waypoints is better than nothing) , and to make things worse, even use of console brings up those errors.

please add handling of missing .tilecache

**Comment by stephendade** [comment]
Done in #277. I'll close this when it's been merged in
