### ISSUE TITLE
[feature request] Support python3

### ISSUE THREAD

**Issue by richerlariviere** [ArduPilot/MAVProxy#280]
Do you plan to port MAVProxy to python 3?

**Comment by stephendade** [comment]
It'd be awesome to do that. The only issue holding us back is that wxPython (which we use for our GUI) is itself not compatible with Python 3.

The non-gui parts of MAVproxy could definitely be ported. The pymavlink package (backend UAV protocol library) would need to be ported.

**Comment by monkeypants** [comment]
wxPython 4.0 is out in BETA,  https://wxpython.org/

The pypi listing says it supports python 3.4, 3.5 and 3.6.

**Comment by stephendade** [comment]
And there's a pull request at #420 to do exactly that. There were some concerns about breaking Python 2.7 compatbility though

**Comment by amilcarlucas** [comment]
Try the latest version.

**Comment by amilcarlucas** [comment]
Works in the latest release. Closing it now. Please reopen if the problem persists in the latest release.
