### ISSUE TITLE
logfile location

### ISSUE THREAD

**Issue by hblanken** [ArduPilot/MAVProxy#285]
Great new improvements to Mavproxy, thank you! 

I am setting the log directory to --state-basedir=/var/www/html  and this works well with standard mavproxy commands.
Then I want to execute in daemon mode. I believe there is an issue with the logfile location when running with --daemon option. The logfile always wants to write to: "Log Directory: /var/log Telemetry log: /var/log/mav.tlog" even when I set the log directory. This can cause permission rights issues when executing. I have now resorted to increasing the permission rights for the /var/log folder. But this is just a work around. Could you again bind the logfile location to the --state-basedir location? Thank you

**Comment by stephendade** [comment]
Fixed in #299
