### ISSUE TITLE
error using sim_vehicle.py -w showing c\users\Stephen fixed path

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/MAVProxy#303]
I don't know what version of MAVproxy I'm running, is there a way to check? The file is dated June 15, 2016 which matches 1.5.0 so I'm assuming that's it.
I ran command: `sim_vehicle.py -j4 -S10 -w` and this popped up.
I would have brushed it off except it showed the error in the fixed path of:
C:\Users\Stephen\Documents\MAVProxy\MAVProxy\build\mavproxy\out00-PYZ.py

![mavproxy_error](https://cloud.githubusercontent.com/assets/4782875/17745856/69d2e8a4-6462-11e6-8c63-dd37d2a84319.png)

**Comment by stephendade** [comment]
To get the current version:
```
module load help
mavhelp about
```

The references to "C:\Users\Stephen\Documents\MAVProxy" are expected. It's a side effect of when I compile MAVProxy on my computer.

**Comment by peterbarker** [comment]
@magicrub is this repeatable?

The exception looks genuine - it tried to open a file (at a seemingly reasonable location (for Windows...)) and failed.  Have you previously had a MAVProxy installed which you've manually deleted or something?

You could always try reinstalling...

If the exception doesn't happen any more then we could probably close this issue as @stephendade has explained it's an artifact of the build process for Windows.

**Comment by stephendade** [comment]
Fixed in MAVProxy 1.6.1
