### ISSUE TITLE
Graph scaling

### ISSUE THREAD

**Issue by Georacer** [ArduPilot/MAVProxy#313]
Hello everyone,

This is part bug report, part me scratching my head.

I was trying to make my simulator work with SITL again and I was debugging the acceleration feed via `graph RAW_IMU.zacc`

For default ArduCopter SITL, it looks something like this.
![screenshot from 2016-09-16 15-00-14](https://cloud.githubusercontent.com/assets/3149996/18585486/d667bbe6-7c1f-11e6-8f52-f3fea0b4750a.png)

For my ArduPlane simulation, it looks something like this.
![screenshot from 2016-09-16 15-02-39](https://cloud.githubusercontent.com/assets/3149996/18585495/e7f5e2ac-7c1f-11e6-957b-7e2967db0524.png)
So far, so good. The difference in value is probably because I use g=9.81.

But when the spiks go out of range and the figure autoscales around -991, it looks like this:
![screenshot from 2016-09-16 15-06-58](https://cloud.githubusercontent.com/assets/3149996/18585527/196dfd6a-7c20-11e6-8112-71460d702854.png)

I can see the multiplier up top, but I still can't explain the reading of -0.2.

Is this a bug or is it me?
Cheers!

**Comment by stephendade** [comment]
Fixed in #361
