### ISSUE TITLE
Error in web page description - stop and stop

### ISSUE THREAD

**Issue by sjaramillo10** [ArduPilot/MAVProxy#314]
URL: ../cuav_module/index
Title: Image Processing with cuav

Under the Usage subtitle, the third paragraph says 'These commands stop and stop the image capturing...', I think it should be: 'These commands **start** and stop the image capturing...'.

(I just highlighted the start word to show it is the one that should be corrected)

**Comment by stephendade** [comment]
Fixed. Thanks for letting us know!

http://ardupilot.github.io/MAVProxy/html/cuav_module/index.html
