### ISSUE TITLE
Garbage on screen when passing mavlink traffic through mavproxy

### ISSUE THREAD

**Issue by larsks** [ArduPilot/MAVProxy#344]
I'm starting mavproxy (1.5.7) like this, with master connected to a radio modem and then a udb broadcast available for connecting a GUI ground control like qgroundcontrol or apm planner:

    mavproxy --master /dev/ttyUSB0 --out udpbcast:0.0.0.0:14550

This works fine; mavproxy is able to connect and qgroundcontrol is able to connect.  The problem is that I get garbage dumped onto the screen periodically, like this:

    (j;R0:>::Fd:VU ^O/SB$6''Q:31;t?:>:Y(.;z	>7-\\ _^HA;K> E] <<+C=*'>.I>wtBs:_>E3qw;3 <OcD=ZJJbQ\t

Because this will frequently dropped random characters in the midst of output of mavproxy it can lead to confusing, hard to read output.

I have seen this behavior under both Linux (Fedora 24) and Mac OS X (recent-ish), and it happens regardless of whether I am using apm planner or qgroundcontrol.

**Comment by peterbarker** [comment]
On Fri, 11 Nov 2016, Lars Kellogg-Stedman wrote:

> This works fine; mavproxy is able to connect and qgroundcontrol is able to
> connect. The problem is that I get garbage dumped onto the screen
> periodically, like this:
> 
> (j;R0:>::Fd:VU ^O/SB$6''Q:31;t?:>:Y(.;z	>7-\\ _^HA;K> E] <<+C=*'>.I>wtBs:_>E3
> qw;3 <OcD=ZJJbQ\t
> 
> Because this will frequently dropped random characters in the midst of
> output of mavproxy it can lead to confusing, hard to read output.

Radio links are noisy; by default MAVProxy shows you any corrupted data 
that comes in.

Try "set shownoise 0"
