### ISSUE TITLE
MAVExplorer throwing an Error loading file when there is space on the path or at file name

### ISSUE THREAD

**Issue by juvinski** [ArduPilot/MAVProxy#388]
Hi,

if you try to open a file using the MAVExplorer GUI, selecting MAVExplorer Open, if there is a space in the file name or path the log file will not be opened and on console you will receive a
MAV> Error loading file.

At command line if you call MAVExplorer and there is space on file name or path everything works.

**Comment by stephendade** [comment]
This has been fixed for some time. Closing.
