### ISSUE TITLE
Add documentation on how to add new joystick mappings

### ISSUE THREAD

**Issue by stephendade** [ArduPilot/MAVProxy#398]
@larsks - could we get some instructions on how users can add new joystick mappings? They could go in the MAVProxy documentation branch (gh-pages).

For reference, current joystick documentation is at http://ardupilot.github.io/MAVProxy/html/modules/joystick.html

**Comment by larsks** [comment]
The original patch included documentation in https://github.com/ArduPilot/MAVProxy/blob/master/docs/JOYSTICKS.md.

**Comment by stephendade** [comment]
Thanks! I've added a link to that in the MAVProxy documentation at http://ardupilot.github.io/MAVProxy/html/modules/joystick.html
