### ISSUE TITLE
high memory usage

### ISSUE THREAD

**Issue by kd0aij** [ArduPilot/MAVProxy#403]
mavexplorer running on Ubuntu 16.04 with 2 graphs displayed (over 600MB consumed per graph):
![mavexplorer_mem](https://cloud.githubusercontent.com/assets/2300221/24867108/68e91654-1dc9-11e7-96ef-e8a2e5666bcf.png)

**Comment by stephendade** [comment]
How large was the log file you had running in MAVExplorer. 

It does use a lot of memory with larger logfiles

**Comment by kd0aij** [comment]
The log file was about 30MB, quite small compared to the memory usage.

**Comment by peterbarker** [comment]
On Tue, 11 Apr 2017, Mark Whitehorn wrote:

> The log file was about 30MB, quite small compared to the memory usage.

There are two problems.  The first is this 20-to-1 size expansion.

The second is that every graph you create creates an out-and-out copy of 
the data.

Both need fixing :-)

**Comment by swaroophangal** [comment]
Hello. My logfile size is ~250MB. I love this tool, but my machine conks off everytime i run this tools with a logfile of this size. Any other suggestions with the feature set as that of this tool? Or any other route to analyze data of that size?

**Comment by peterbarker** [comment]
On Fri, 3 Aug 2018, swaroophangal wrote:

> Hello. My logfile size is ~250MB. I love this tool, but my machine conks off everytime i run this tools with a logfile of this size. Any other suggestions
> with the feature set as that of this tool? Or any other route to analyze data of that size?

I'm assuming you're talking MAVExplorer here :-)

We're *quite* aware of the memory problems - a lot of swearing has been 
done over the matter....

You have a few options.  One is to trim the log to pieces of interest - 
there's mavextract.py and mavlogdump.py's `--condition` option to do that.

Most people point to apmplanner2 as the best graphing tool out there - you 
might give that a shot.

There's also the "dron.ee" tool now-adays, but I haven't played with 
that...

**Comment by amilcarlucas** [comment]
The latest version uses a lot less memory

**Comment by amilcarlucas** [comment]
Works in the latest release. Closing it now. Please reopen if the problem persists in the latest release.
