### ISSUE TITLE
MAVExplorer not opening AC3.5-rc7 logs

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/MAVProxy#417]
MAVExplorer has "Issue loading file" with *.bin and *.log from rc7. Logs are not corrupted, and open in MP-latest for log analysis.

**Comment by peterbarker** [comment]
Supply a sample, please.

**Comment by auturgy** [comment]
https://drive.google.com/drive/folders/0B21eBYNmOfAKQjV2ZU94S2t1dnc
None of these open in mavexplorer (win10)

**Comment by peterbarker** [comment]
No problems under Linux.  Please post the text of the error.

**Comment by auturgy** [comment]
"Error loading file" in console

**Comment by peterbarker** [comment]
That's not... particularly informative :-)  Is there a stack trace on stdout?

**Comment by peterbarker** [comment]
Actually, that's only called if no argument is supplied.  There was a problem when logs had spaces in the filename - is that the case for the files you're supplying?

**Comment by auturgy** [comment]
they're the generated filenames - I'll check

**Comment by auturgy** [comment]
yes, spaces in the filename between date and time.

**Comment by auturgy** [comment]
I just renamed one - still no open, same brief error msg.

**Comment by stephendade** [comment]
I've renamed the files to have no spaces in them. They open/graph for me. Using MAVProxy 1.4.42 on Win10

**Comment by auturgy** [comment]
I think windows hates me. Might just build up a Linux box and save the frustration.

Regards,

James

**Comment by peterbarker** [comment]
@auturgy 

https://github.com/peterbarker/MAVProxy/commit/2f21cfc1ae8c08ecbb30bdc5157a6a5a1c0ee1d7#diff-e6b1d8e5a4cc4e1a493c3da49b991ab5R431

That patch should have made the error message longer.  It did, didn't it?

**Comment by auturgy** [comment]
Yes: posted the output in gitter on Saturday 

Regards,

James

**Comment by auturgy** [comment]
Closing.  Unsure what changed, but now working.  Suggest operator error or windows being windows.
