### ISSUE TITLE
MAVProxy continuously overriding streamrates.

### ISSUE THREAD

**Issue by jaxxzer** [ArduPilot/MAVProxy#431]
I think mavproxy should configure stream rates once upon connection, instead of setting the stream rates in [periodic_tasks](https://github.com/ArduPilot/MAVProxy/blob/master/MAVProxy/mavproxy.py#L731).

If we are using mavproxy as a bridge to a GCS, then the GCS cannot configure its own stream rates, and the user cannot configure the stream rates from parameter editors without the parameter being quickly overwritten by mavproxy.

**Comment by amilcarlucas** [comment]
just use parameter --stream-rate=-1

**Comment by amilcarlucas** [comment]
Works in the latest release. Closing it now. Please reopen if the problem persists in the latest release.
