### ISSUE TITLE
Download and Installation - 

### ISSUE THREAD

**Issue by monkeypants** [ArduPilot/MAVProxy#447]
URL: ../getting_started/download_and_installation
Title: Download and Installation

The debian instructions say to `apt-get install ... python-lxml ...`. For me, using a recent raspbian-lite, this was not sufficient. I also needed to install `libxml2-dev`. This mat be a broken dependency in python-lxml raspbian package.

**Comment by stephendade** [comment]
Fixed in documentation at http://ardupilot.github.io/MAVProxy/html/getting_started/download_and_installation.html
