### ISSUE TITLE
Download and Installation - 

### ISSUE THREAD

**Issue by ShingoMatsuura** [ArduPilot/MAVProxy#451]
URL: ../getting_started/download_and_installation
Title: Download and Installation linsux

Please add this pip commad before pip insall Mavproxy

pip install future lxml

**Comment by stephendade** [comment]
The future and lxml packages are usually installed as part of pymavlink, which in turn is installed as part of MAVProxy. Could you post the exact steps that caused your error?

**Comment by ShingoMatsuura** [comment]
Thank you for your comment. I followed this site steps.

http://ardupilot.github.io/MAVProxy/html/getting_started/download_and_installation.html#linux

**Comment by stephendade** [comment]
Which operating system and version? Are you able to post the output of the commands? - it would help in diagnosing the issue.

**Comment by auturgy** [comment]
Suggest close.  Updates have been released to both pymavlink and mavproxy.
