### ISSUE TITLE
MAVCesium Updates

### ISSUE THREAD

**Issue by brizey02** [ArduPilot/MAVProxy#457]
Might merge the MAVCesium with the latest changes.

**Comment by SamuelDudley** [comment]
Yes, this was on my list of things to do after cleaning up the readme.md as there is still some out of date content. Hopefully I'll get around to tidying it up this weekend.

**Comment by SamuelDudley** [comment]
I have opened a PR to update the MAVCesium submodule #458

**Comment by SamuelDudley** [comment]
Fixed with #458

**Comment by auturgy** [comment]
This can be closed. @peterbarker @stephendade
