### ISSUE TITLE
Possible bug setting parameters?

### ISSUE THREAD

**Issue by nickponline** [ArduPilot/MAVProxy#46]
I encountered [this exception](https://www.dropbox.com/s/t0jv8pepsl5llqj/Screenshot%202014-04-17%2014.59.55.png) while running:

```
param set TRIM_ARSPD_CM 1300
```

**Comment by amilcarlucas** [comment]
Never saw this one, it is probably fixed now.

**Comment by nickponline** [comment]
Yeah, I posted that over 4 years ago :)

**Comment by amilcarlucas** [comment]
Works in the latest release. Closing it now. Please reopen if the problem persists in the latest release.
