### ISSUE TITLE
Differential GPS - module load using caps

### ISSUE THREAD

**Issue by Coolaswa** [ArduPilot/MAVProxy#464]
URL: ../modules/dgps
Title: Differential GPS

On the wiki page the command to use the dgps module is 'module load dpgs', while this does not work. The command 'module load DGPS' does work. 
If someone could update the wiki page I would appreciate it, I recently spent quite some time figuring this out and might save someone else a load of time.

**Comment by stephendade** [comment]
Patch merged in
