### ISSUE TITLE
support for spektrum dx8 with OrangeRX USB dongle joystick

### ISSUE THREAD

**Issue by peteretep** [ArduPilot/MAVProxy#492]
Adding basic support for a [ spektrum dx8 controller ](http://www.spektrumrc.com/Products/Default.aspx?ProdID=SPM8015) with an [OrangeRX usb dongle](https://hobbyking.com/en_us/orange-rx-dsmx-dsm2-compatible-protocol-usb-dongle-flight-simulator.html)

**Comment by stephendade** [comment]
Added in 39025a770470a09b641642a4a2a66524b574568b
