### ISSUE TITLE
MAVExplorer - typo in docs

### ISSUE THREAD

**Issue by EbinPhilip** [ArduPilot/MAVProxy#517]
URL: ../analysis/mavexp
Title: MAVExplorer

The command given in the page is wrong. It should be MAVExplorer.py and not mavexplorer.py. It would be best if this page can just be linked to http://ardupilot.org/dev/docs/using-mavexplorer-for-log-analysis.html

**Comment by stephendade** [comment]
Fixed in eb87378c10fb9a80544df56ea660e3c19d314368
