### ISSUE TITLE
Missing Startup Options / Descriptions

### ISSUE THREAD

**Issue by Yendolosch** [ArduPilot/MAVProxy#520]
URL: ../getting_started/starting
Title: Startup Options

* The startup option `--source-component` is missing a description,  
* `--non-interactive` should be listed along with its `--daemon` equivalent, and  
* `--default` is actually called `--default-modules`.

**Comment by stephendade** [comment]
Fixed in eb87378c10fb9a80544df56ea660e3c19d314368
