### ISSUE TITLE
Frequently Asked Questions and Issues - some typos

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/MAVProxy#523]
URL: ../getting_started/faq
Title: Frequently Asked Questions and Issues

use ArduPlane, ArduCopter etc in preference to APM:Plane etc.
Also, regarding other mavlink compatible firmwares, the sentence is missing a "not" (ie "however may NOT display all flight data"

**Comment by stephendade** [comment]
Fixed in Wiki
