### ISSUE TITLE
TLOG file corrupted by line ending translations on WIndows

### ISSUE THREAD

**Issue by newts** [ArduPilot/MAVProxy#535]
@peterbarker  this is the issue we gittered about last week

I traced this back to file opening not in binary mode in mavproxy.py.  There could be other binary files with similar problem?

I have tested the fix and will file the pull request shortly.

**Comment by amilcarlucas** [comment]
Looks like this one can be closed.

**Comment by amilcarlucas** [comment]
Works in the latest release. Closing it now. Please reopen if the problem persists in the latest release.
