### ISSUE TITLE
Minor bug (logic) in mavproxy_rc.py

### ISSUE THREAD

**Issue by oriondream** [ArduPilot/MAVProxy#59]
Description:
- Invalid channel id is not handled properly. Python's exception message reported instead of custom exception message
- RC overriding cancelation is not working due to wrong/inappropriate value for cancellation. It should be 0 instead of 65535

Related bug/pull request:
#42 #57

Solution: 
In function cmd_rc of mavproxy_rc.py please replace the code segment
        if value == -1:
            value = 65535
        if args[0] == 'all':
            for i in range(8):
                self.override[i] = value
        else:
            channel = int(args[0])
            self.override[channel - 1] = value
            if channel < 1 or channel > 8:
                print("Channel must be between 1 and 8 or 'all'")
                return
with the following code:
        if value == -1:
            value = 0
        if args[0] == 'all':
            for i in range(8):
                self.override[i] = value
        else:
            channel = int(args[0])
            if channel < 1 or channel > 8:
                print("Channel must be between 1 and 8 or 'all'")
                return
            else:
                self.override[channel - 1] = value

Thanks,
Regards,

**Comment by amilcarlucas** [comment]
Both PRs have been merged, closing this
