### ISSUE TITLE
Tab Completion on MacOS

### ISSUE THREAD

**Issue by jpfeltracco** [ArduPilot/MAVProxy#591]
On my MacOS machine I noticed tab completion wasn't working for me. I found in the code that "gnureadline" was being imported instead of just readline.

I had both installed on my machine, but only after removing the gnureadline import was I able to get tab completion working again.

**Comment by srmainwaring** [comment]
Hi @jpfeltracco, reviewing old tickets. I can't reproduce running on macOS Monterey (tab completion working fine). Please reopen if you are still seeing this issue.
