### ISSUE TITLE
RangeFinder how to check????

### ISSUE THREAD

**Issue by karu2003** [ArduPilot/MAVProxy#596]
I have 9 sensors RangeFinder how to check each sensor?  In the last master there may be 10 of them.

**Comment by peterbarker** [comment]
`status` contains all the messages we are getting from the autopilot.

The `DISTANCE_SENSOR` message has an ID in it.

You might find `mavlogdump.py --t DISTANCE_SENSOR mav.tlog` helpful.

Reopen this issue with more details if you need more help.
