### ISSUE TITLE
parameter editor module ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [ArduPilot/MAVProxy#625]
In [List of project ideas for GSoC 2019](http://ardupilot.org/dev/docs/gsoc-ideas-list.html#list-of-suggested-projects-for-gsoc-2019) there was the idea of improving the  MAVProxy GCS with adding a parameter module.

Can I have more information about what wants to be done in this module ?

**Comment by MohamedAliRashad** [comment]
@peterbarker @tridge Any ideas ?

**Comment by peterbarker** [comment]
Some coordination with @Akshath-Singhal  would be good here.  @Akshath-Singhal is working on MAVProxy as part of GSoC - but we haven't nailed down exact deliverables yet.

@Akshath-Singhal - did you have specific ideas you'd like to share on this topic?

**Comment by Akshath-Singhal** [comment]
The basic idea here was to create a GUI with a grid displaying all the parameters, quite similar to the one usually observed in Mission Planner. The deliverables are not yet discussed with the mentors but incremental search, displaying description, and reading and writing from file would be core components. I have my end semester exams going on currently but I will try to provide a rough GUI for feedback as soon as possible.

**Comment by MohamedAliRashad** [comment]
@Akshath-Singhal 
Great, i would love to help you (if you don't mind) with this as i needs to sharpen my python skills more.
We can use this issue for Coordinating what needs to be reached and to know what i can help you with.

Don't push things to fast, i have exams too ^ ^

**Comment by Akshath-Singhal** [comment]
@MohamedAliRashad I will be having a discussion with @peterbarker and @tridge soon regarding the GSOC project. As soon as we are done with it, I will create a blog post detailing the deliverables. If you have some specific features you would like to be included then let me know. I will include it in the discussion.

I would be happy to work collaboratively on this. However, I am not sure how GSOC rules deal with any such issue. I will try to keep everyone updated regarding my future plans and current progress related to the project .

**Comment by MohamedAliRashad** [comment]
@Akshath-Singhal This is off GSoC ... i made a promise that i will contribute to Ardupilot this year whether i was accepted or not.

I can suggest features for the project but i need to know first the main framework we will be working in.

**Comment by Akshath-Singhal** [comment]
@MohamedAliRashad You can track the progress of parameter editor module here https://github.com/ArduPilot/MAVProxy/pull/635. I believe this issue should be closed now.
