### ISSUE TITLE
Copter: add support to switch to ZIGZAG mode from command line

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MAVProxy#687]
The next stable release of ArduPilot Copter includes ZigZag mode.  It would be nice if we could switch to this mode easily from the command line by typing ZIGZAG.  Currently we need to switch using "mode 24" but this is a little cumbersome as I always forget the number.

**Comment by peterbarker** [comment]
```
STABILIZE> zigzag
STABILIZE> Got MAVLink msg: COMMAND_ACK {command : 11, result : 0}
ZIGZAG> Mode ZIGZAG
```

This is probably just waiting on a stable pymalink release.  MAVProxy uses the mode mapping present in `mavutil.py` in there.

**Comment by rmackay9** [comment]
ok thanks..
