### ISSUE TITLE
MAVProxy Mission Editor problem on Windows 10

### ISSUE THREAD

**Issue by imfatant** [ArduPilot/MAVProxy#690]
Hi,

I'm getting the following error when trying to open the Mission Editor window:

MANUAL> Adding link /dev/ttyS115
Connect /dev/ttyS115 source_system=255
Failed to connect to /dev/ttyS115 : [Errno 13] could not open port /dev/ttyS115: [Errno 13] Permission denied: '/dev/ttyS115'

It did work a few moments ago!

I am using WSL Ubuntu with Xming.

Thanks :)

EDIT: I should mention that the reason I am using WSL is that MAVProxy under native Windows is killing  the forwarding connection I have set up to talk to a MAVSDK-based code I'm developing. MAVProxy under WSL doesn't kill the connection.

EDIT: When I run MAVProxy as root, I get a different error:

Failed to connect to /dev/ttyS115 : [Errno 5] could not open port /dev/ttyS115: [Errno 5] Input/output error: '/dev/ttyS115'

**Comment by stephendade** [comment]
Works with latest installer on https://firmware.ardupilot.org/Tools/MAVProxy/
