### ISSUE TITLE
Download and Installation - 

### ISSUE THREAD

**Issue by muexxl** [ArduPilot/MAVProxy#734]
URL: ../getting_started/download_and_installation
Title: Download and Installation

Please update this description and the issue title

`sudo apt-get install python3-dev python3-opencv python3-wxgtk3.0 python3-pip python3-matplotlib python3-pygame python3-lxml python3-yaml`

python3-wxgtk3.0 cannot be found anymore. It should be replaced by python3-wxgtk**4.0**

`sudo apt-get install python3-dev python3-opencv python3-wxgtk4.0 python3-pip python3-matplotlib python3-pygame python3-lxml python3-yaml`

**Comment by auturgy** [comment]
Closed by https://github.com/ArduPilot/MAVProxy/pull/764
