### ISSUE TITLE
MAVFlightView on Windows 10 not working

### ISSUE THREAD

**Issue by kd0aij** [ArduPilot/MAVProxy#794]
version: MAVProxySetup-latest.exe | Sat Aug 8 11:37:10 2020
groundtrack not displayed on map
sample log: https://drive.google.com/file/d/1KachGTaV05Re_RTRRTeNUvGta8zy3EiE/view?usp=sharing
Ubuntu 18.04 (WSL) on left, Windows native on right:
![image](https://user-images.githubusercontent.com/2300221/89716465-758a9a80-d96a-11ea-90c6-17a19c0baf13.png)

**Comment by stephendade** [comment]
Works fine for me:
![Screenshot from 2020-08-11 17-03-09](https://user-images.githubusercontent.com/1731976/89867611-c281a180-dbf4-11ea-8c22-1cf106b05eff.png)

Try downloading and re-installing and see if that fixes it.

**Comment by kd0aij** [comment]
Repeated download/install and it is now working properly
