### ISSUE TITLE
Mission Editor: Default Alt persistently resets to 100

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MAVProxy#812]
It would be nice if the Default Alt field would maintain the last value set at least within the sessions (i.e. until MAVProxy is rebooted).  It would be even better if it maintained the value across boots.  It is especially annoying that it resets to the default after the "Read WPs" button is pressed because this is quite a common thing to do.

![image](https://user-images.githubusercontent.com/1498098/93032771-34269280-f66e-11ea-8a4a-182d937d5fd1.png)

**Comment by peterbarker** [comment]
On Sun, 13 Sep 2020, Randy Mackay wrote:

> It would be nice if the Default Alt field would maintain the last value set at least within the sessions (i.e. until MAVProxy is rebooted). It would be
> even better if it maintained the value across boots. It is especially annoying that it resets to the default after the "Read WPs" button is pressed
> because this is quite a common thing to do.

You can set the default value of this with `set wpalt`

That can be done in your .mavinit.scr

**Comment by rmackay9** [comment]
@peterbarker, great, thanks for your help.

**Comment by rmackay9** [comment]
@peterbarker, is it possible to do something similar for the Guided "Fly-To-Here" menu option?

**Comment by peterbarker** [comment]
On Mon, 14 Sep 2020, Randy Mackay wrote:

> @peterbarker, is it possible to do something similar for the Guided "Fly-To-Here" menu option?

https://github.com/ArduPilot/MAVProxy/pull/815
