### ISSUE TITLE
MAVLink XML

### ISSUE THREAD

**Issue by DecSander** [ArduPilot/MAVProxy#86]
Hey, so I'm not sure if this is an issue with MAVLink/MAVProxy or FlightGear, but I figured I'd put it here since the MAVLink community is more responsive than the FlightGear one.  So I'm running a HIL and I discovered that when I load the FG Simulator with MAVLink:
--generic=socket,out,40,localhost,5501,udp,MAVLink 
--generic=socket,in,45,localhost,5502,udp,MAVLink
It is close to working, but for some reason the packets are only 132 bytes instead of the required 140 that MAVProxy asks for.  Any Help would be much appreciated!

**Comment by monkeypants** [comment]
what was the resolution?
